name: Build centos7.9 rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: build with dockerfile
      run: cd centos-7.9-rust && docker build -t centos-7.9-rust .



