name: Run test

on:
  workflow_dispatch:

# permissions: write-all

env:
  REPO_GIT_BRANCH: ${GITHUB_REF_NAME}
  REPO_GIT_HASH: ${{ github.sha }}

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
    #   deployments: write
      contents: write
    #   packages: write
    #   actions: read|write|none
    #   checks: read|write|none
      
    #   id-token: read|write|none
    #   issues: read|write|none
    #   discussions: read|write|none
      
    #   pages: read|write|none
    #   pull-requests: read|write|none
    #   repository-projects: read|write|none
    #   security-events: read|write|none
    #   statuses: read|write|none
  
    steps:
    - uses: actions/checkout@v3

    - name: display git
      run: |
        echo "REPO_GIT_BRANCH=$REPO_GIT_BRANCH"
        echo "REPO_GIT_HASH=$REPO_GIT_HASH"
        
    - name: make out file
      shell: bash
      run: ./run-me.sh make_out_file

    - name: make env.ASSET
      run: |
        echo "ASSET=$(./run-me.sh out_file_path)" >> $GITHUB_ENV
        echo "ASSET=${{ env.ASSET }}"

    # - name: Release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     name: latest
    #     prerelease: true
    #     files: |
    #         ${{ env.ASSET }}

    - name: Release latest
      uses: "diillson/auto-release@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ${{ env.ASSET }}
    
    - name: where is scp
      shell: bash
      run: whereis scp
      
    - name: which scp
      shell: bash
      run: which scp
    

