name: Run container

on:
  workflow_dispatch:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  REPO_GIT_HASH: ${{ github.sha }}

jobs:
  build:

    runs-on: ubuntu-latest
    container: simonfucn/centos-7.9-rust:latest

    steps:
    - uses: actions/checkout@v3

    - name: display repo git hash
      run: echo REPO_GIT_HASH=$REPO_GIT_HASH

    - name: display rust version
      run: rustup --version

    - name: display clang version
      run: |
        ps -p $$
        echo "$SHELL"
        source scl_source enable llvm-toolset-7 || true
        clang --version
        echo REPO_GIT_HASH=$REPO_GIT_HASH
        
    - name: display clang version2
      shell: bash
      run: |
        clang --version

    - name: display dump_syms version
      run: dump_syms --version



